name: studio_projects
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

#------------------packages---------------------------#

dependencies:
  flutter:
    sdk: flutter

  #utility packages
  http: ^1.3.0
  logger: ^2.4.0
  flutter_native_splash: ^2.4.1
  url_launcher: ^6.3.0
  smooth_page_indicator: ^1.2.0+3
  carousel_slider: ^5.0.0


  #Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  #State management:
  get: ^4.6.6
  get_storage: ^2.1.1

  cookie_jar: ^4.0.8

  #product specific
  intl: ^0.19.0

  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1

  firebase_core: ^3.8.1
  firebase_analytics: ^11.3.6


#---------------./ Packages End-------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

#----------LOCAL ASSETS---------------#

  assets:

    - assests/icons/brands/
    - assests/images/
    - assests/logos/
    - assests/images/catagory/
    - assests/images/banner/
    - assests/images/product/


#----------LOCAL FONTS-----------------#

  fonts:
    - family: Poppins
      fonts:
        - asset: assests/fonts/coolvetica rg.otf
          weight: 300
        - asset: assests/fonts/coolvetica rg it.otf
          weight: 300
          style: italic
        - asset: assests/fonts/poppins.bold.ttf
          weight: 400
        - asset: assests/fonts/poppins.bold-italic.ttf
          weight: 500
          style: italic
        - asset: assests/fonts/poppins.italic.ttf
          weight: 300
          style: italic
        - asset: assests/fonts/poppins.light.ttf
          weight: 300
        - asset: assests/fonts/poppins.light-italic.ttf
          weight: 300
          style: italic
        - asset: assests/fonts/poppins.medium.ttf
          weight: 400
        - asset: assests/fonts/poppins.medium-italic.ttf
          weight: 400
          style: italic
        - asset: assests/fonts/poppins.regular.ttf
          weight: 300
        - asset: assests/fonts/poppins.semibold.ttf
          weight: 500
        - asset: assests/fonts/poppins.semibold-italic.ttf
          weight: 500
          style: italic

