// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWfiAkyoAKNbMTRXnGN86n6UaojGA3d_I',
    appId: '1:699170207760:web:6dfdffa3f6c55827573295',
    messagingSenderId: '699170207760',
    projectId: 'ecommerce-b24cc',
    authDomain: 'ecommerce-b24cc.firebaseapp.com',
    storageBucket: 'ecommerce-b24cc.firebasestorage.app',
    measurementId: 'G-79DX08GZX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEikU64gsVk86BJyNAwIeJAvK6Y3852Vw',
    appId: '1:699170207760:android:aee38e1b7306e14f573295',
    messagingSenderId: '699170207760',
    projectId: 'ecommerce-b24cc',
    storageBucket: 'ecommerce-b24cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS2vGOa2cupi6x3ILac6kwBXbJDUErjqk',
    appId: '1:699170207760:ios:3ff2af9a4699341e573295',
    messagingSenderId: '699170207760',
    projectId: 'ecommerce-b24cc',
    storageBucket: 'ecommerce-b24cc.firebasestorage.app',
    iosBundleId: 'com.example.studioProjects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS2vGOa2cupi6x3ILac6kwBXbJDUErjqk',
    appId: '1:699170207760:ios:3ff2af9a4699341e573295',
    messagingSenderId: '699170207760',
    projectId: 'ecommerce-b24cc',
    storageBucket: 'ecommerce-b24cc.firebasestorage.app',
    iosBundleId: 'com.example.studioProjects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWfiAkyoAKNbMTRXnGN86n6UaojGA3d_I',
    appId: '1:699170207760:web:fdff40935a60bfd6573295',
    messagingSenderId: '699170207760',
    projectId: 'ecommerce-b24cc',
    authDomain: 'ecommerce-b24cc.firebaseapp.com',
    storageBucket: 'ecommerce-b24cc.firebasestorage.app',
    measurementId: 'G-RMB5M7XEBW',
  );
}
